server:
    port: 8081

spring:
    jpa:
        hibernate:
            ddl-auto: update

    data:
        mongodb:
            host: localhost # default
            port: 27017 # default
            database: user-db
