server:
    port: 8081

spring:
    datasource:
        url: jdbc:postgresql://ec2-18-203-62-227.eu-west-1.compute.amazonaws.com:5432/d3mgknnv1ss6hs
        username: lbbhrpsnwzbuiz
        password: 569fee4610ed3aceb0e0289dfe25727b3e3697befb1a08142d3a6885526f43ef

    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
